version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: wine-postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5433:5432"
    volumes:
      - wine_pg_data:/var/lib/postgresql/data

volumes:
  wine_pg_data:
