version: '3.8'

services:
  postgres-app:
    image: postgres:15
    container_name: wine-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  wine-app:
    build: .
    container_name: wine-app
    depends_on:
      - postgres-app
    restart: always
    ports:
      - "8081:8081"
    environment:
      - DB_URL=postgres://postgres:postgres@postgres-app:5432/postgres?sslmode=disable

volumes:
  postgres_data:
